app = "creepy-crawlie-cinema-club"

kill_signal = "SIGINT"
kill_timeout = 5

[env]
  MIX_ENV = "prod"
  GMAIL_APP_PASSWORD = ""
  GMAIL_USERNAME = ""

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 4000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "5s"
    interval = "10s"
    restart_limit = 6
    timeout = "2s"